### ISSUE TITLE
Feature: Registrere tid i en timer fremfor Record

### ISSUE THREAD

**Issue by kbilsted** [mvno/Okanshi#26]
I dag kan man kalde `Record()` på en BasicTimer for at tage tid. Jeg kunne tænke mig mulighed for at angive en tid feks via en `Record(TimeSpan t)`. Jeg ønsker at visualisere tid der ikke afvikles inde i en enkelt lambda

**Comment by kichristensen** [comment]
@kbilsted In the current beta there is support something like this, but instead of a method an OkanshiTimer is use. The documentation is not updated yet, but you see the tests, [BasicTimerTest.cs#L105](https://github.com/mvno/Okanshi/blob/b067fa0b41d974c72d226bb24453f64deb366ab6/tests/Okanshi.Tests/BasicTimerTest.cs#L105).
Also this is further enhanced in #27, which adds a Register method which can be passed an int64, with the amount of milliseconds to register.
The next version will contain the requested functionality.
